
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_db
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dll-auto: none
  liquibase:
    change-log: "classpath:/db/changelog/2023/10/25-01-changelog.xml"
    enabled: true

server:
  port: 8191
